/* Verilog module instantiation template generated by SCUBA Diamond_3.1_Production (93) */
/* Module Version: 5.5 */
/* Thu May 29 20:36:38 2014 */

/* parameterized module instance */
my_pll __ (.CLK( ), .CLKOP( ), .CLKOK( ), .LOCK( ));
